name: Run syntax checks and tests for Python

on:
  workflow_call:
    inputs:
      run-environments:
        description: List of OS to run test on
        type: string
        default: '["ubuntu-22.04", "macos-latest", "windows-latest"]'
      python-versions:
        description: Python versions to test
        type: string
        default: '["3.8", "3.9", "3.10", "3.11"]'
      hw-test-flag:
        description: Name of flag used to mark tests dependent on HW
        type: string
        default: needs_hardware
      

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(inputs.python-versions) }}
        os: ${{ fromJSON(inputs.run-environments) }}
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install -e .[test]
          python -m pip install flake8~=6.0
      - name: Lint with flake8
        run: |
          flake8 --exclude .venv
      - name: Test with pytest
        run: |
          pytest -m "not ${{ inputs.hw-test-flag }}" --cov-report term --junitxml=test-report.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: "test-report*.xml"
