name: Create Github Release

on:
  workflow_call:
    inputs:
      release-notes:
        description: Release notes to add to the release
        type: string
        default: ""

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >-
          gh release create
          '${{ github.ref_name }}'
          --repo '${{ github.repository }}'
          --notes "${{ inputs.release-notes }}"
      - name: Upload metadata.yml to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Upload metadata.yml to GitHub Release using the `gh` CLI.
        run: >-
          gh release upload
          '${{ github.ref_name }}' metadata.yml
          --repo '${{ github.repository }}'
