name: Create Github Release

on:
  workflow_call:
    inputs:
      release-notes:
        description: Release notes to add to the release
        type: string
        default: ""

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "$(gh release view '${{ github.ref_name }}' 2>&1)" == "release not found" ]]; then
            gh release create '${{ github.ref_name }}' --repo '${{ github.repository }}' --notes "${{ inputs.release-notes }}"
          fi
      - name: Upload metadata.yml to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Upload metadata.yml to GitHub Release using the `gh` CLI.
        run: >-
          gh release upload
          '${{ github.ref_name }}' metadata.yml
          --repo '${{ github.repository }}'
  create-driver-index-release:
    needs: create-github-release
    uses: sensirion/.github/.github/workflows/driver_index.common.create_release.yml@main
    secrets:
      DI_BASIC_AUTH_TOKEN: ${{ secrets.DI_BASIC_AUTH_TOKEN }}
    with:
      DI_BASE_URL: ${{ vars.DI_BASE_URL }}
