name: Arduino Library Quality Check
# Description: Running Arduino Lint and Arduino CI
# NOTICE: This shared workflow is likely used by several others in this folder

on:
  workflow_call:
    inputs:
      expect-arduino-examples:
        description: Should examples be expected ?
        required: false
        type: boolean
        default: true
      lint-lib-manager-check:
        description: Configuration of the checks for publication on the 'Arduino Library Manager'. Options are "false", "submit", and "update".
        required: false
        type: string
        default: "false"
      fqbn:
        description: names of libraries to build as yaml list
        required: false
        type: string
        default: "[\"esp32:esp32:esp32\"]"

jobs:
  arduino-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: ${{ inputs.lint-lib-manager-check }}

  arduino-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fqbn: ${{fromJSON(inputs.fqbn)}}
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/compile-sketches@v1
        with: 
          fqbn: ${{ matrix.fqbn }}
          sketch-paths: |
            - ./examples
        env:
          EXPECT_EXAMPLES: ${{ inputs.expect-arduino-examples }}
