name: Build sphinx documentation and publish as github page

on:
  workflow_call:
    inputs:
      run-environment:
        description: OS to run TODO check on
        type: string
        default: "ubuntu-22.04"
      build-python-version:
        description: Python version used for docs build
        type: string
        default: 3.11
      docs-dir:
        description: directory where the python docs are
        type: string
        default: "./docs"

jobs:
  build_pages:
    runs-on: ${{ inputs.run-environment }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.build-python-version }}
          cache: "pip"
      - name: Install the project dependencies
        run: |
          python setup.py install
          python -m pip install -r ${{ inputs.docs-dir }}/requirements.txt
      - name: Build documentation
        run: cd ${{ inputs.docs-dir }} && make html
      - name: Upload html
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ inputs.docs-dir }}/_build/html
  deploy_pages:
    runs-on: ${{ inputs.run-environment }}
    needs: build_pages
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source
    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          token: ${{secrets.GITHUB_TOKEN}}
