name: Check for TODO in code

on:
  workflow_call:
    inputs:
      run-environment:
        description: OS to run TODO check on
        type: string
        default: "ubuntu-22.04"
      additional-parameters:
        description: additional parameters to grep, e.g. you can add additional files/folder to be excluded
        type: string
        default: ""

jobs:
  validate:
    strategy:
      fail-fast: false
    runs-on: ${{ inputs.run-environment }}
    steps:
      - uses: actions/checkout@v4
      - name: Check TODO
        shell: bash
        run: |
          ! grep -rnw --exclude=.gitlab-ci.yml --exclude-dir=.git --exclude-dir=.github ${{ inputs.additional-parameters }} . -e "TODO"
